export const startProject = {
  delivery: {
    provider: 'Formspree',
    form: 'CWT Project Inquiries',
    endpoint: 'https://formspree.io/f/mwlegrkd',
    recipient: 'createwithtimi@gmail.com',
  },
  hero: {
    eyebrow: 'Start a Project / 001',
    title: ['Have a story?', "Let's find the", 'world inside it.'],
    body: "Bring us the story, brand, community, character, culture or idea. We'll figure out what it could become.",
    reassurance: {
      title: "You don't need a finished brief.",
      body: "That's part of what we can help shape.",
    },
  },
  steps: [
    {
      id: 'around',
      number: '01',
      question: ['What are we', 'building around?'],
      hint: 'Help us understand the heart of your world.',
      type: 'single',
      options: [
        'Brand',
        'Sport',
        'Music',
        'Culture',
        'Hospitality',
        'Original IP / Character',
        'Product',
        'Something else',
      ],
    },
    {
      id: 'bringing',
      number: '02',
      question: ['What are', 'you bringing?'],
      hint: 'Where are you starting from?',
      type: 'single',
      options: [
        'An idea',
        'An existing story or IP',
        'A brand or product',
        'A community or audience',
        'Something already in motion',
        "I'm still figuring it out",
      ],
    },
    {
      id: 'destinations',
      number: '03',
      question: ['Where could', 'it go?'],
      hint: 'What expressions excite you?',
      type: 'multiple',
      options: [
        'Story / Comic',
        'Interactive Experience',
        'Film / Motion',
        'Graphics / Campaign',
        'Apparel',
        'Cards / Collectibles',
        'Something unexpected',
        'Not sure — help me figure it out',
      ],
    },
  ],
  details: {
    number: '04',
    question: ['Tell us a little', 'about it.'],
    hint: 'A few details so we can understand what you are trying to shape.',
    fields: {
      name: 'Your name',
      email: 'Email address',
      organization: 'Organization / brand',
      description: 'Tell us about your project',
      timeline: 'Project timeline',
      budget: 'Budget context',
    },
    timelineChoices: [
      'As soon as possible',
      'Within 1–3 months',
      'Within 3–6 months',
      '6+ months',
      'No fixed timeline',
    ],
    budgetChoices: [
      'Exploring',
      'Small / focused project',
      'Mid-scale project',
      'Larger world / campaign',
      "Let's discuss",
    ],
  },
  submit: {
    title: ["Let's build", 'the world.'],
    action: 'Send project',
    submitting: 'Sending project...',
    success: {
      eyebrow: 'Project received.',
      title: ['The first step', 'is done.', "Now let's see", 'where this', 'could go.'],
      body: "Thanks for sharing your project with CreateWithTimi. We'll review what you've sent and continue the conversation by email.",
      cta: 'View our work',
      href: '/#work',
    },
    error: {
      title: "We couldn't send that yet.",
      body: 'Your project details are still here. Please try again.',
    },
  },
};
